name: Lint

on:
  workflow_call:
  pull_request:
    branches:
      - "main"

jobs:
  lint:
    name: Lint with Ruff
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install python
        run: uv python install
      - name: Install the project
        run: uv sync --all-groups
      - name: Run Ruff linter
        run: uv run ruff check .
      - name: Run Ruff import sorter
        run: uv run ruff check --select I .
      - name: Run Ruff formatter
        run: uv run ruff format --check .
