name: Publish to PyPI

on:
  workflow_dispatch:
  release:
    types:
      - "created"

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml
  test:
    name: Test
    uses: ./.github/workflows/test.yml
    secrets: inherit
  publish:
    name: Publish to PyPI
    needs: [lint, test]
    runs-on: ubuntu-latest
    environment:
      name: PyPI
      url: https://pypi.org/project/drf-pydantic
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install python
        run: uv python install
      - name: Install the project
        run: uv sync --all-groups
      - name: Build
        run: uv build
      - name: Publish
        run: uv publish --token ${{ secrets.PYPI_TOKEN }}
